behaviors:
  WalkerAgentMulti:
    trainer_type: ppo
    time_horizon: 128
    max_steps: 1.0e7
    hyperparameters:
      batch_size: 128
      beta: 0.01
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0003
      num_epoch: 3
    network_settings:
      num_layers: 2
      normalize: true
      hidden_units: 256
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      gail:
        strength: 0.001
        gamma: 0.99
        demo_path: Assets/Demonstrations
      curiosity:
        strength: 0.001
        gamma: 0.99
        network_settings:
          hidden_units: 256
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 1000
    summary_freq: 30000
    behavioral_cloning:
      demo_path: Assets/Demonstrations
      strength: 0.3
      steps: 500000
